---
version: "3.9"
services:
  pyroscope:
    image: "pyroscope/pyroscope:latest"
    ports:
      - "4040:4040"
    command:
      - "server"
  app:
    build: .
    environment:
      - PYROSCOPE_APPLICATION_NAME=optaplanner
      - PYROSCOPE_PROFILING_INTERVAL=10ms
      - PYROSCOPE_PROFILER_EVENT=itimer
      - PYROSCOPE_PROFILER_ALLOC=4k
      - PYROSCOPE_UPLOAD_INTERVAL=8s
      - PYROSCOPE_SAMPLING_DURATION=2s
      - PYROSCOPE_FORMAT=jfr
      - PYROSCOPE_SAMPLING_EVENT_ORDER=itimer,alloc
      - PYROSCOPE_LOG_LEVEL=debug
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
      - PYROSCOPE_AUTH_TOKEN=abc123
    ports:
      - "8080:8080"
