{
  "formatVersion": "1.1",
  "component": {
    "group": "io.pyroscope",
    "module": "agent",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "agent-2.7.0.jar",
          "url": "agent-2.7.0.jar",
          "size": 5719998,
          "sha512": "6fe3c56c3030fabecd2fc022cede9e0fa8e2c92ee4a14a4c641ca622a19e585e79f3a454f709bf8e0fac18f97e5c6011689b385f1c0cbf0bd53f72e8dcb84831",
          "sha256": "7b1d48d7e02352a0773b787b0f33192f4297d85e97512b6e16bf5cc0cd386706",
          "sha1": "7fb80cc7e51c42fd54c3b2655f80e4d5e8af560d",
          "md5": "c7b0094ea18d1b50d1a2e77be405367d"
        }
      ]
    }
  ]
}
