{
  "formatVersion": "1.1",
  "component": {
    "group": "io.pyroscope",
    "module": "agent",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "agent-2.7.0.jar",
          "url": "agent-2.7.0.jar",
          "size": 5725654,
          "sha512": "5fffb630447bfd46df0bdc10489f3facdc82df9efbfd1a4e840cbf51213a02f6f98e72be675852739c27efc1d817dabde32cfb5f4a372cd6dbe71d92627b8e83",
          "sha256": "c60a6faac39b75221a97961b1ea949ce2833a9a843c593136ddf932319b0beaa",
          "sha1": "c68d3b30e80ce8dbc1edeb821bd050ac647e23f1",
          "md5": "7257641a7067b23e55c0f8b981a046bc"
        }
      ]
    }
  ]
}
