// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jfr_labels.proto

package io.pyroscope.labels.pb;

public final class JfrLabels {
  private JfrLabels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContextOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.pyroscope.labels.pb.Context)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */
    int getLabelsCount();
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */
    boolean containsLabels(
        long key);
    /**
     * Use {@link #getLabelsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, java.lang.Long>
    getLabels();
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */
    java.util.Map<java.lang.Long, java.lang.Long>
    getLabelsMap();
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */

    long getLabelsOrDefault(
        long key,
        long defaultValue);
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */

    long getLabelsOrThrow(
        long key);
  }
  /**
   * Protobuf type {@code io.pyroscope.labels.pb.Context}
   */
  public static final class Context extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.pyroscope.labels.pb.Context)
      ContextOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Context.newBuilder() to construct.
    private Context(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Context() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Context();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Context(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                labels_ = com.google.protobuf.MapField.newMapField(
                    LabelsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
              labels__ = input.readMessage(
                  LabelsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              labels_.getMutableMap().put(
                  labels__.getKey(), labels__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Context_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetLabels();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Context_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pyroscope.labels.pb.JfrLabels.Context.class, io.pyroscope.labels.pb.JfrLabels.Context.Builder.class);
    }

    public static final int LABELS_FIELD_NUMBER = 1;
    private static final class LabelsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, java.lang.Long>newDefaultInstance(
                  io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Context_LabelsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.Long> labels_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
    internalGetLabels() {
      if (labels_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            LabelsDefaultEntryHolder.defaultEntry);
      }
      return labels_;
    }

    public int getLabelsCount() {
      return internalGetLabels().getMap().size();
    }
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */

    @java.lang.Override
    public boolean containsLabels(
        long key) {
      
      return internalGetLabels().getMap().containsKey(key);
    }
    /**
     * Use {@link #getLabelsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.Long> getLabels() {
      return getLabelsMap();
    }
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Long, java.lang.Long> getLabelsMap() {
      return internalGetLabels().getMap();
    }
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */
    @java.lang.Override

    public long getLabelsOrDefault(
        long key,
        long defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.Long> map =
          internalGetLabels().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, int64&gt; labels = 1;</code>
     */
    @java.lang.Override

    public long getLabelsOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.Long> map =
          internalGetLabels().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetLabels(),
          LabelsDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Long, java.lang.Long> entry
           : internalGetLabels().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, java.lang.Long>
        labels__ = LabelsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, labels__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.pyroscope.labels.pb.JfrLabels.Context)) {
        return super.equals(obj);
      }
      io.pyroscope.labels.pb.JfrLabels.Context other = (io.pyroscope.labels.pb.JfrLabels.Context) obj;

      if (!internalGetLabels().equals(
          other.internalGetLabels())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetLabels().getMap().isEmpty()) {
        hash = (37 * hash) + LABELS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetLabels().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Context parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.pyroscope.labels.pb.JfrLabels.Context prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.pyroscope.labels.pb.Context}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.pyroscope.labels.pb.Context)
        io.pyroscope.labels.pb.JfrLabels.ContextOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Context_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetLabels();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableLabels();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Context_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pyroscope.labels.pb.JfrLabels.Context.class, io.pyroscope.labels.pb.JfrLabels.Context.Builder.class);
      }

      // Construct using io.pyroscope.labels.pb.JfrLabels.Context.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableLabels().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Context_descriptor;
      }

      @java.lang.Override
      public io.pyroscope.labels.pb.JfrLabels.Context getDefaultInstanceForType() {
        return io.pyroscope.labels.pb.JfrLabels.Context.getDefaultInstance();
      }

      @java.lang.Override
      public io.pyroscope.labels.pb.JfrLabels.Context build() {
        io.pyroscope.labels.pb.JfrLabels.Context result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.pyroscope.labels.pb.JfrLabels.Context buildPartial() {
        io.pyroscope.labels.pb.JfrLabels.Context result = new io.pyroscope.labels.pb.JfrLabels.Context(this);
        int from_bitField0_ = bitField0_;
        result.labels_ = internalGetLabels();
        result.labels_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pyroscope.labels.pb.JfrLabels.Context) {
          return mergeFrom((io.pyroscope.labels.pb.JfrLabels.Context)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pyroscope.labels.pb.JfrLabels.Context other) {
        if (other == io.pyroscope.labels.pb.JfrLabels.Context.getDefaultInstance()) return this;
        internalGetMutableLabels().mergeFrom(
            other.internalGetLabels());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pyroscope.labels.pb.JfrLabels.Context parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pyroscope.labels.pb.JfrLabels.Context) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Long, java.lang.Long> labels_;
      private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
      internalGetLabels() {
        if (labels_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              LabelsDefaultEntryHolder.defaultEntry);
        }
        return labels_;
      }
      private com.google.protobuf.MapField<java.lang.Long, java.lang.Long>
      internalGetMutableLabels() {
        onChanged();;
        if (labels_ == null) {
          labels_ = com.google.protobuf.MapField.newMapField(
              LabelsDefaultEntryHolder.defaultEntry);
        }
        if (!labels_.isMutable()) {
          labels_ = labels_.copy();
        }
        return labels_;
      }

      public int getLabelsCount() {
        return internalGetLabels().getMap().size();
      }
      /**
       * <code>map&lt;int64, int64&gt; labels = 1;</code>
       */

      @java.lang.Override
      public boolean containsLabels(
          long key) {
        
        return internalGetLabels().getMap().containsKey(key);
      }
      /**
       * Use {@link #getLabelsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, java.lang.Long> getLabels() {
        return getLabelsMap();
      }
      /**
       * <code>map&lt;int64, int64&gt; labels = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Long, java.lang.Long> getLabelsMap() {
        return internalGetLabels().getMap();
      }
      /**
       * <code>map&lt;int64, int64&gt; labels = 1;</code>
       */
      @java.lang.Override

      public long getLabelsOrDefault(
          long key,
          long defaultValue) {
        
        java.util.Map<java.lang.Long, java.lang.Long> map =
            internalGetLabels().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int64, int64&gt; labels = 1;</code>
       */
      @java.lang.Override

      public long getLabelsOrThrow(
          long key) {
        
        java.util.Map<java.lang.Long, java.lang.Long> map =
            internalGetLabels().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearLabels() {
        internalGetMutableLabels().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int64, int64&gt; labels = 1;</code>
       */

      public Builder removeLabels(
          long key) {
        
        internalGetMutableLabels().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, java.lang.Long>
      getMutableLabels() {
        return internalGetMutableLabels().getMutableMap();
      }
      /**
       * <code>map&lt;int64, int64&gt; labels = 1;</code>
       */
      public Builder putLabels(
          long key,
          long value) {
        
        
        internalGetMutableLabels().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int64, int64&gt; labels = 1;</code>
       */

      public Builder putAllLabels(
          java.util.Map<java.lang.Long, java.lang.Long> values) {
        internalGetMutableLabels().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.pyroscope.labels.pb.Context)
    }

    // @@protoc_insertion_point(class_scope:io.pyroscope.labels.pb.Context)
    private static final io.pyroscope.labels.pb.JfrLabels.Context DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.pyroscope.labels.pb.JfrLabels.Context();
    }

    public static io.pyroscope.labels.pb.JfrLabels.Context getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Context>
        PARSER = new com.google.protobuf.AbstractParser<Context>() {
      @java.lang.Override
      public Context parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Context(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Context> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Context> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.pyroscope.labels.pb.JfrLabels.Context getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SnapshotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.pyroscope.labels.pb.Snapshot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */
    int getContextsCount();
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */
    boolean containsContexts(
        long key);
    /**
     * Use {@link #getContextsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
    getContexts();
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */
    java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
    getContextsMap();
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */

    io.pyroscope.labels.pb.JfrLabels.Context getContextsOrDefault(
        long key,
        io.pyroscope.labels.pb.JfrLabels.Context defaultValue);
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */

    io.pyroscope.labels.pb.JfrLabels.Context getContextsOrThrow(
        long key);

    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */
    int getStringsCount();
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */
    boolean containsStrings(
        long key);
    /**
     * Use {@link #getStringsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Long, java.lang.String>
    getStrings();
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */
    java.util.Map<java.lang.Long, java.lang.String>
    getStringsMap();
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */

    java.lang.String getStringsOrDefault(
        long key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */

    java.lang.String getStringsOrThrow(
        long key);
  }
  /**
   * Protobuf type {@code io.pyroscope.labels.pb.Snapshot}
   */
  public static final class Snapshot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.pyroscope.labels.pb.Snapshot)
      SnapshotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Snapshot.newBuilder() to construct.
    private Snapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Snapshot() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Snapshot();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Snapshot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                contexts_ = com.google.protobuf.MapField.newMapField(
                    ContextsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
              contexts__ = input.readMessage(
                  ContextsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              contexts_.getMutableMap().put(
                  contexts__.getKey(), contexts__.getValue());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                strings_ = com.google.protobuf.MapField.newMapField(
                    StringsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Long, java.lang.String>
              strings__ = input.readMessage(
                  StringsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              strings_.getMutableMap().put(
                  strings__.getKey(), strings__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Snapshot_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetContexts();
        case 2:
          return internalGetStrings();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Snapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pyroscope.labels.pb.JfrLabels.Snapshot.class, io.pyroscope.labels.pb.JfrLabels.Snapshot.Builder.class);
    }

    public static final int CONTEXTS_FIELD_NUMBER = 1;
    private static final class ContextsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>newDefaultInstance(
                  io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Snapshot_ContextsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  io.pyroscope.labels.pb.JfrLabels.Context.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> contexts_;
    private com.google.protobuf.MapField<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
    internalGetContexts() {
      if (contexts_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ContextsDefaultEntryHolder.defaultEntry);
      }
      return contexts_;
    }

    public int getContextsCount() {
      return internalGetContexts().getMap().size();
    }
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */

    @java.lang.Override
    public boolean containsContexts(
        long key) {
      
      return internalGetContexts().getMap().containsKey(key);
    }
    /**
     * Use {@link #getContextsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> getContexts() {
      return getContextsMap();
    }
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> getContextsMap() {
      return internalGetContexts().getMap();
    }
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */
    @java.lang.Override

    public io.pyroscope.labels.pb.JfrLabels.Context getContextsOrDefault(
        long key,
        io.pyroscope.labels.pb.JfrLabels.Context defaultValue) {
      
      java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> map =
          internalGetContexts().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
     */
    @java.lang.Override

    public io.pyroscope.labels.pb.JfrLabels.Context getContextsOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> map =
          internalGetContexts().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int STRINGS_FIELD_NUMBER = 2;
    private static final class StringsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Long, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Long, java.lang.String>newDefaultInstance(
                  io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Snapshot_StringsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Long, java.lang.String> strings_;
    private com.google.protobuf.MapField<java.lang.Long, java.lang.String>
    internalGetStrings() {
      if (strings_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StringsDefaultEntryHolder.defaultEntry);
      }
      return strings_;
    }

    public int getStringsCount() {
      return internalGetStrings().getMap().size();
    }
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */

    @java.lang.Override
    public boolean containsStrings(
        long key) {
      
      return internalGetStrings().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStringsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.Long, java.lang.String> getStrings() {
      return getStringsMap();
    }
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.Long, java.lang.String> getStringsMap() {
      return internalGetStrings().getMap();
    }
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getStringsOrDefault(
        long key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Long, java.lang.String> map =
          internalGetStrings().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, string&gt; strings = 2;</code>
     */
    @java.lang.Override

    public java.lang.String getStringsOrThrow(
        long key) {
      
      java.util.Map<java.lang.Long, java.lang.String> map =
          internalGetStrings().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetContexts(),
          ContextsDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetStrings(),
          StringsDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> entry
           : internalGetContexts().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
        contexts__ = ContextsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, contexts__);
      }
      for (java.util.Map.Entry<java.lang.Long, java.lang.String> entry
           : internalGetStrings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Long, java.lang.String>
        strings__ = StringsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, strings__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.pyroscope.labels.pb.JfrLabels.Snapshot)) {
        return super.equals(obj);
      }
      io.pyroscope.labels.pb.JfrLabels.Snapshot other = (io.pyroscope.labels.pb.JfrLabels.Snapshot) obj;

      if (!internalGetContexts().equals(
          other.internalGetContexts())) return false;
      if (!internalGetStrings().equals(
          other.internalGetStrings())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetContexts().getMap().isEmpty()) {
        hash = (37 * hash) + CONTEXTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetContexts().hashCode();
      }
      if (!internalGetStrings().getMap().isEmpty()) {
        hash = (37 * hash) + STRINGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStrings().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pyroscope.labels.pb.JfrLabels.Snapshot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.pyroscope.labels.pb.JfrLabels.Snapshot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.pyroscope.labels.pb.Snapshot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.pyroscope.labels.pb.Snapshot)
        io.pyroscope.labels.pb.JfrLabels.SnapshotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Snapshot_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetContexts();
          case 2:
            return internalGetStrings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableContexts();
          case 2:
            return internalGetMutableStrings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Snapshot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pyroscope.labels.pb.JfrLabels.Snapshot.class, io.pyroscope.labels.pb.JfrLabels.Snapshot.Builder.class);
      }

      // Construct using io.pyroscope.labels.pb.JfrLabels.Snapshot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableContexts().clear();
        internalGetMutableStrings().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pyroscope.labels.pb.JfrLabels.internal_static_io_pyroscope_labels_pb_Snapshot_descriptor;
      }

      @java.lang.Override
      public io.pyroscope.labels.pb.JfrLabels.Snapshot getDefaultInstanceForType() {
        return io.pyroscope.labels.pb.JfrLabels.Snapshot.getDefaultInstance();
      }

      @java.lang.Override
      public io.pyroscope.labels.pb.JfrLabels.Snapshot build() {
        io.pyroscope.labels.pb.JfrLabels.Snapshot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.pyroscope.labels.pb.JfrLabels.Snapshot buildPartial() {
        io.pyroscope.labels.pb.JfrLabels.Snapshot result = new io.pyroscope.labels.pb.JfrLabels.Snapshot(this);
        int from_bitField0_ = bitField0_;
        result.contexts_ = internalGetContexts();
        result.contexts_.makeImmutable();
        result.strings_ = internalGetStrings();
        result.strings_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pyroscope.labels.pb.JfrLabels.Snapshot) {
          return mergeFrom((io.pyroscope.labels.pb.JfrLabels.Snapshot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pyroscope.labels.pb.JfrLabels.Snapshot other) {
        if (other == io.pyroscope.labels.pb.JfrLabels.Snapshot.getDefaultInstance()) return this;
        internalGetMutableContexts().mergeFrom(
            other.internalGetContexts());
        internalGetMutableStrings().mergeFrom(
            other.internalGetStrings());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pyroscope.labels.pb.JfrLabels.Snapshot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pyroscope.labels.pb.JfrLabels.Snapshot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> contexts_;
      private com.google.protobuf.MapField<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
      internalGetContexts() {
        if (contexts_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ContextsDefaultEntryHolder.defaultEntry);
        }
        return contexts_;
      }
      private com.google.protobuf.MapField<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
      internalGetMutableContexts() {
        onChanged();;
        if (contexts_ == null) {
          contexts_ = com.google.protobuf.MapField.newMapField(
              ContextsDefaultEntryHolder.defaultEntry);
        }
        if (!contexts_.isMutable()) {
          contexts_ = contexts_.copy();
        }
        return contexts_;
      }

      public int getContextsCount() {
        return internalGetContexts().getMap().size();
      }
      /**
       * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
       */

      @java.lang.Override
      public boolean containsContexts(
          long key) {
        
        return internalGetContexts().getMap().containsKey(key);
      }
      /**
       * Use {@link #getContextsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> getContexts() {
        return getContextsMap();
      }
      /**
       * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> getContextsMap() {
        return internalGetContexts().getMap();
      }
      /**
       * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
       */
      @java.lang.Override

      public io.pyroscope.labels.pb.JfrLabels.Context getContextsOrDefault(
          long key,
          io.pyroscope.labels.pb.JfrLabels.Context defaultValue) {
        
        java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> map =
            internalGetContexts().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
       */
      @java.lang.Override

      public io.pyroscope.labels.pb.JfrLabels.Context getContextsOrThrow(
          long key) {
        
        java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> map =
            internalGetContexts().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearContexts() {
        internalGetMutableContexts().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
       */

      public Builder removeContexts(
          long key) {
        
        internalGetMutableContexts().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context>
      getMutableContexts() {
        return internalGetMutableContexts().getMutableMap();
      }
      /**
       * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
       */
      public Builder putContexts(
          long key,
          io.pyroscope.labels.pb.JfrLabels.Context value) {
        
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableContexts().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int64, .io.pyroscope.labels.pb.Context&gt; contexts = 1;</code>
       */

      public Builder putAllContexts(
          java.util.Map<java.lang.Long, io.pyroscope.labels.pb.JfrLabels.Context> values) {
        internalGetMutableContexts().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Long, java.lang.String> strings_;
      private com.google.protobuf.MapField<java.lang.Long, java.lang.String>
      internalGetStrings() {
        if (strings_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StringsDefaultEntryHolder.defaultEntry);
        }
        return strings_;
      }
      private com.google.protobuf.MapField<java.lang.Long, java.lang.String>
      internalGetMutableStrings() {
        onChanged();;
        if (strings_ == null) {
          strings_ = com.google.protobuf.MapField.newMapField(
              StringsDefaultEntryHolder.defaultEntry);
        }
        if (!strings_.isMutable()) {
          strings_ = strings_.copy();
        }
        return strings_;
      }

      public int getStringsCount() {
        return internalGetStrings().getMap().size();
      }
      /**
       * <code>map&lt;int64, string&gt; strings = 2;</code>
       */

      @java.lang.Override
      public boolean containsStrings(
          long key) {
        
        return internalGetStrings().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStringsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, java.lang.String> getStrings() {
        return getStringsMap();
      }
      /**
       * <code>map&lt;int64, string&gt; strings = 2;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.Long, java.lang.String> getStringsMap() {
        return internalGetStrings().getMap();
      }
      /**
       * <code>map&lt;int64, string&gt; strings = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getStringsOrDefault(
          long key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Long, java.lang.String> map =
            internalGetStrings().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int64, string&gt; strings = 2;</code>
       */
      @java.lang.Override

      public java.lang.String getStringsOrThrow(
          long key) {
        
        java.util.Map<java.lang.Long, java.lang.String> map =
            internalGetStrings().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStrings() {
        internalGetMutableStrings().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int64, string&gt; strings = 2;</code>
       */

      public Builder removeStrings(
          long key) {
        
        internalGetMutableStrings().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Long, java.lang.String>
      getMutableStrings() {
        return internalGetMutableStrings().getMutableMap();
      }
      /**
       * <code>map&lt;int64, string&gt; strings = 2;</code>
       */
      public Builder putStrings(
          long key,
          java.lang.String value) {
        
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableStrings().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int64, string&gt; strings = 2;</code>
       */

      public Builder putAllStrings(
          java.util.Map<java.lang.Long, java.lang.String> values) {
        internalGetMutableStrings().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.pyroscope.labels.pb.Snapshot)
    }

    // @@protoc_insertion_point(class_scope:io.pyroscope.labels.pb.Snapshot)
    private static final io.pyroscope.labels.pb.JfrLabels.Snapshot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.pyroscope.labels.pb.JfrLabels.Snapshot();
    }

    public static io.pyroscope.labels.pb.JfrLabels.Snapshot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Snapshot>
        PARSER = new com.google.protobuf.AbstractParser<Snapshot>() {
      @java.lang.Override
      public Snapshot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Snapshot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Snapshot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Snapshot> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.pyroscope.labels.pb.JfrLabels.Snapshot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyroscope_labels_pb_Context_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pyroscope_labels_pb_Context_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyroscope_labels_pb_Context_LabelsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pyroscope_labels_pb_Context_LabelsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyroscope_labels_pb_Snapshot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pyroscope_labels_pb_Snapshot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyroscope_labels_pb_Snapshot_ContextsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pyroscope_labels_pb_Snapshot_ContextsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pyroscope_labels_pb_Snapshot_StringsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pyroscope_labels_pb_Snapshot_StringsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020jfr_labels.proto\022\026io.pyroscope.labels." +
      "pb\"u\n\007Context\022;\n\006labels\030\001 \003(\0132+.io.pyros" +
      "cope.labels.pb.Context.LabelsEntry\032-\n\013La" +
      "belsEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\003:\0028" +
      "\001\"\216\002\n\010Snapshot\022@\n\010contexts\030\001 \003(\0132..io.py" +
      "roscope.labels.pb.Snapshot.ContextsEntry" +
      "\022>\n\007strings\030\002 \003(\0132-.io.pyroscope.labels." +
      "pb.Snapshot.StringsEntry\032P\n\rContextsEntr" +
      "y\022\013\n\003key\030\001 \001(\003\022.\n\005value\030\002 \001(\0132\037.io.pyros" +
      "cope.labels.pb.Context:\0028\001\032.\n\014StringsEnt" +
      "ry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\t:\0028\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_pyroscope_labels_pb_Context_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_pyroscope_labels_pb_Context_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pyroscope_labels_pb_Context_descriptor,
        new java.lang.String[] { "Labels", });
    internal_static_io_pyroscope_labels_pb_Context_LabelsEntry_descriptor =
      internal_static_io_pyroscope_labels_pb_Context_descriptor.getNestedTypes().get(0);
    internal_static_io_pyroscope_labels_pb_Context_LabelsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pyroscope_labels_pb_Context_LabelsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_pyroscope_labels_pb_Snapshot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_pyroscope_labels_pb_Snapshot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pyroscope_labels_pb_Snapshot_descriptor,
        new java.lang.String[] { "Contexts", "Strings", });
    internal_static_io_pyroscope_labels_pb_Snapshot_ContextsEntry_descriptor =
      internal_static_io_pyroscope_labels_pb_Snapshot_descriptor.getNestedTypes().get(0);
    internal_static_io_pyroscope_labels_pb_Snapshot_ContextsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pyroscope_labels_pb_Snapshot_ContextsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_pyroscope_labels_pb_Snapshot_StringsEntry_descriptor =
      internal_static_io_pyroscope_labels_pb_Snapshot_descriptor.getNestedTypes().get(1);
    internal_static_io_pyroscope_labels_pb_Snapshot_StringsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pyroscope_labels_pb_Snapshot_StringsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
