{
  "formatVersion": "1.1",
  "component": {
    "group": "io.pyroscope",
    "module": "agent",
    "version": "2.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "agent-2.5.0.jar",
          "url": "agent-2.5.0.jar",
          "size": 5719988,
          "sha512": "b0af630493306347557477bdcb61c17abf0a531a583f407086daeca96338fd5a22f8715f4e1561031d8e985854b87b222efe71a9e18307beb4f12045cfadbd05",
          "sha256": "c80901070136e8992264cbc90f7e4d18ddc063633bc4d4ff56011917a6a6eccb",
          "sha1": "67f4068796640d051360d144715a4c5e40439e2a",
          "md5": "96a0b9b3104a6b1a5d2e3d8a54e5c7e5"
        }
      ]
    }
  ]
}
