{
  "formatVersion": "1.1",
  "component": {
    "group": "io.pyroscope",
    "module": "agent",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "agent-2.6.0.jar",
          "url": "agent-2.6.0.jar",
          "size": 5719935,
          "sha512": "ac69bf1722d37ad3d2cff452dbf39ee7f60213c90b070162923ce95eb9047e67b1a3c6771b9e5fb4018881c0a291caae1a9f23ab807e3569b5d360e94220a9fc",
          "sha256": "7d42cee11393b481a6fffb102ee6f00d06bdc66eed5d479373d41914d5b8e701",
          "sha1": "aa15210c8323f64a9783eb6a2aab5c66e21795eb",
          "md5": "b58950d64dc628fd2ebee82895d924e2"
        }
      ]
    }
  ]
}
