services:
  pyroscope:
    image: "grafana/pyroscope:1.20.3@sha256:47fc578b2227e9c0c5c5efda34966c1566b0d0a0802cb2adc2e1e9f7ae16a7aa"
    ports:
      - "4040:4040"
  app:
    build: .
    environment:
      - PYROSCOPE_APPLICATION_NAME=optaplanner
      - PYROSCOPE_PROFILING_INTERVAL=10ms
      - PYROSCOPE_PROFILER_EVENT=itimer
      - PYROSCOPE_UPLOAD_INTERVAL=1s
      - PYROSCOPE_LOG_LEVEL=debug
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040
      - PYROSCOPE_AUTH_TOKEN=abc123
    ports:
      - "8080:8080"
