name: Deploy Javadoc

on:
  push:
    branches:
      - main

permissions:
  contents: write # pushes to the gh-pages branch

jobs:
  publish:
    runs-on: ubuntu-x64
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Generate Javadoc
        run: ./gradlew javaDoc 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: agent/build/docs/javadoc
          target-folder: javadoc
