name: Deploy Javadoc

on:
  push:
    branches:
      - main

permissions:
  contents: write # pushes to the gh-pages branch

jobs:
  publish:
    runs-on: ubuntu-x64
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Generate Javadoc
        run: ./gradlew javaDoc 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a # v4.7.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: agent/build/docs/javadoc
          target-folder: javadoc
